server {
    listen 80;
    server_name localhost;

    # 1. Serve a Aplicação (Front-end)
    location / {
        root /usr/share/nginx/html;
        index usuario.html index.html;
        try_files $uri $uri/ /usuario.html;
    }

    # 2. Redireciona a API e os Swaggers para o Gateway
    # Tudo que começa com /api é enviado para o gateway interno
    location /api/ {
        proxy_pass http://api-gateway:8080/api/;

        # Headers essenciais para o Swagger funcionar via HTTPS
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}